### ISSUE TITLE
Different color standards

### ISSUE THREAD

**Issue by Gabbalo** [aricooperdavis/grav-plugin-custom-banner#10]
Hi there
I don't know if there is a reason (beside alpha maybe), why you used two different styles of color declaration (html vs. rgb)?
That is a bit confusing and most don't have access to color-codes beside html while not using any converter maybe. 
Even if this might cost the possibility to use alpha values (which on text are a bit questionable and would be understandable on the banner value maybe) I'd suggest the usage of html code everywhere.
To get the banner a bit translucent, you could add a alpha slider separately.

**Comment by Gabbalo** [comment]
Great :)

**Comment by aricooperdavis** [comment]
Actually, it looks like the Grav admin plugin's colorpicker form field [automatically switches from HTML to RGBA when the transparency != 1](](https://github.com/getgrav/grav-plugin-admin/blob/0d16602880413bb6cbc2c94b75f02dce3174d215/themes/grav/app/forms/fields/colorpicker.js#L567)).

As such I think I'll leave this unchanged, using rgba() notation for the background color as the Grav admin plugin enforces, but use html notation for the foreground color to illustrate that this notation can also be used. Unless you think it's worth using rgba() notation for the foreground color too just so they're both in the same notation?

**Comment by Gabbalo** [comment]
Na, leave it then. since I started with "I don't know if there is a reason ..." I now do, there IS one :D
